// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: app/server/datasource/rdbms/ydb/split.proto

package ydb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TSplitDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Shard:
	//
	//	*TSplitDescription_DataShard_
	//	*TSplitDescription_ColumnShard_
	Shard         isTSplitDescription_Shard `protobuf_oneof:"shard"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSplitDescription) Reset() {
	*x = TSplitDescription{}
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSplitDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSplitDescription) ProtoMessage() {}

func (x *TSplitDescription) ProtoReflect() protoreflect.Message {
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSplitDescription.ProtoReflect.Descriptor instead.
func (*TSplitDescription) Descriptor() ([]byte, []int) {
	return file_app_server_datasource_rdbms_ydb_split_proto_rawDescGZIP(), []int{0}
}

func (x *TSplitDescription) GetShard() isTSplitDescription_Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *TSplitDescription) GetDataShard() *TSplitDescription_DataShard {
	if x != nil {
		if x, ok := x.Shard.(*TSplitDescription_DataShard_); ok {
			return x.DataShard
		}
	}
	return nil
}

func (x *TSplitDescription) GetColumnShard() *TSplitDescription_ColumnShard {
	if x != nil {
		if x, ok := x.Shard.(*TSplitDescription_ColumnShard_); ok {
			return x.ColumnShard
		}
	}
	return nil
}

type isTSplitDescription_Shard interface {
	isTSplitDescription_Shard()
}

type TSplitDescription_DataShard_ struct {
	DataShard *TSplitDescription_DataShard `protobuf:"bytes,1,opt,name=data_shard,json=dataShard,proto3,oneof"`
}

type TSplitDescription_ColumnShard_ struct {
	ColumnShard *TSplitDescription_ColumnShard `protobuf:"bytes,2,opt,name=column_shard,json=columnShard,proto3,oneof"`
}

func (*TSplitDescription_DataShard_) isTSplitDescription_Shard() {}

func (*TSplitDescription_ColumnShard_) isTSplitDescription_Shard() {}

type TSplitDescription_DataShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSplitDescription_DataShard) Reset() {
	*x = TSplitDescription_DataShard{}
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSplitDescription_DataShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSplitDescription_DataShard) ProtoMessage() {}

func (x *TSplitDescription_DataShard) ProtoReflect() protoreflect.Message {
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSplitDescription_DataShard.ProtoReflect.Descriptor instead.
func (*TSplitDescription_DataShard) Descriptor() ([]byte, []int) {
	return file_app_server_datasource_rdbms_ydb_split_proto_rawDescGZIP(), []int{0, 0}
}

type TSplitDescription_ColumnShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardIds      []uint64               `protobuf:"varint,1,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSplitDescription_ColumnShard) Reset() {
	*x = TSplitDescription_ColumnShard{}
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSplitDescription_ColumnShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSplitDescription_ColumnShard) ProtoMessage() {}

func (x *TSplitDescription_ColumnShard) ProtoReflect() protoreflect.Message {
	mi := &file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSplitDescription_ColumnShard.ProtoReflect.Descriptor instead.
func (*TSplitDescription_ColumnShard) Descriptor() ([]byte, []int) {
	return file_app_server_datasource_rdbms_ydb_split_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TSplitDescription_ColumnShard) GetShardIds() []uint64 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

var File_app_server_datasource_rdbms_ydb_split_proto protoreflect.FileDescriptor

var file_app_server_datasource_rdbms_ydb_split_proto_rawDesc = string([]byte{
	0x0a, 0x2b, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72, 0x64, 0x62, 0x6d, 0x73, 0x2f, 0x79, 0x64,
	0x62, 0x2f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x4e,
	0x59, 0x71, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70,
	0x70, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x52, 0x44, 0x42, 0x4d, 0x53, 0x2e, 0x59, 0x64, 0x62, 0x22, 0xb7, 0x02,
	0x0a, 0x11, 0x54, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x4e, 0x59, 0x71, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52,
	0x44, 0x42, 0x4d, 0x53, 0x2e, 0x59, 0x64, 0x62, 0x2e, 0x54, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x68, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x72, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4d, 0x2e, 0x4e, 0x59, 0x71, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52,
	0x44, 0x42, 0x4d, 0x53, 0x2e, 0x59, 0x64, 0x62, 0x2e, 0x54, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x53, 0x68, 0x61, 0x72, 0x64, 0x1a, 0x0b, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x53, 0x68, 0x61,
	0x72, 0x64, 0x1a, 0x2a, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x53, 0x68, 0x61, 0x72,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x42, 0x07,
	0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x66, 0x71, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d,
	0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72, 0x64, 0x62, 0x6d, 0x73, 0x2f, 0x79,
	0x64, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_app_server_datasource_rdbms_ydb_split_proto_rawDescOnce sync.Once
	file_app_server_datasource_rdbms_ydb_split_proto_rawDescData []byte
)

func file_app_server_datasource_rdbms_ydb_split_proto_rawDescGZIP() []byte {
	file_app_server_datasource_rdbms_ydb_split_proto_rawDescOnce.Do(func() {
		file_app_server_datasource_rdbms_ydb_split_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_server_datasource_rdbms_ydb_split_proto_rawDesc), len(file_app_server_datasource_rdbms_ydb_split_proto_rawDesc)))
	})
	return file_app_server_datasource_rdbms_ydb_split_proto_rawDescData
}

var file_app_server_datasource_rdbms_ydb_split_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_server_datasource_rdbms_ydb_split_proto_goTypes = []any{
	(*TSplitDescription)(nil),             // 0: NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription
	(*TSplitDescription_DataShard)(nil),   // 1: NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.DataShard
	(*TSplitDescription_ColumnShard)(nil), // 2: NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.ColumnShard
}
var file_app_server_datasource_rdbms_ydb_split_proto_depIdxs = []int32{
	1, // 0: NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.data_shard:type_name -> NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.DataShard
	2, // 1: NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.column_shard:type_name -> NYql.Connector.App.Server.DataSource.RDBMS.Ydb.TSplitDescription.ColumnShard
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_server_datasource_rdbms_ydb_split_proto_init() }
func file_app_server_datasource_rdbms_ydb_split_proto_init() {
	if File_app_server_datasource_rdbms_ydb_split_proto != nil {
		return
	}
	file_app_server_datasource_rdbms_ydb_split_proto_msgTypes[0].OneofWrappers = []any{
		(*TSplitDescription_DataShard_)(nil),
		(*TSplitDescription_ColumnShard_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_server_datasource_rdbms_ydb_split_proto_rawDesc), len(file_app_server_datasource_rdbms_ydb_split_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_server_datasource_rdbms_ydb_split_proto_goTypes,
		DependencyIndexes: file_app_server_datasource_rdbms_ydb_split_proto_depIdxs,
		MessageInfos:      file_app_server_datasource_rdbms_ydb_split_proto_msgTypes,
	}.Build()
	File_app_server_datasource_rdbms_ydb_split_proto = out.File
	file_app_server_datasource_rdbms_ydb_split_proto_goTypes = nil
	file_app_server_datasource_rdbms_ydb_split_proto_depIdxs = nil
}
