action_id: trunk-cache-prune
date: 2024-05-04 10:13:18
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714817598
full_timestamp:
  nanos: 561190000
  seconds: 1714817598
trunk_version: 1.22.0
