FROM ghcr.io/ydb-platform/fq-connector-go:base

LABEL org.opencontainers.image.source=https://github.com/ydb-platform/fq-connector-go

COPY app/server/config/config.prod.yaml /opt/ydb/cfg/fq-connector-go.yaml
COPY fq-connector-go /opt/ydb/bin/fq-connector-go

CMD ["/opt/ydb/bin/fq-connector-go", "server", "-c", "/opt/ydb/cfg/fq-connector-go.yaml"]
