// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: app/config/client.proto

package config

import (
	common "github.com/ydb-platform/fq-connector-go/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connector client configuration
type TClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connector GRPC API endpoint to connect
	ConnectorServerEndpoint *common.TGenericEndpoint `protobuf:"bytes,4,opt,name=connector_server_endpoint,json=connectorServerEndpoint,proto3" json:"connector_server_endpoint,omitempty"`
	// TLS credentials for Connector
	Tls *TClientTLSConfig `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	// Data source instance we read data from
	DataSourceInstance *common.TGenericDataSourceInstance `protobuf:"bytes,3,opt,name=data_source_instance,json=dataSourceInstance,proto3" json:"data_source_instance,omitempty"`
	// Solomon metrics endpoint to connect
	MetricsServerEndpoint *common.TGenericEndpoint `protobuf:"bytes,5,opt,name=metrics_server_endpoint,json=metricsServerEndpoint,proto3" json:"metrics_server_endpoint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TClientConfig) Reset() {
	*x = TClientConfig{}
	mi := &file_app_config_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TClientConfig) ProtoMessage() {}

func (x *TClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TClientConfig.ProtoReflect.Descriptor instead.
func (*TClientConfig) Descriptor() ([]byte, []int) {
	return file_app_config_client_proto_rawDescGZIP(), []int{0}
}

func (x *TClientConfig) GetConnectorServerEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.ConnectorServerEndpoint
	}
	return nil
}

func (x *TClientConfig) GetTls() *TClientTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *TClientConfig) GetDataSourceInstance() *common.TGenericDataSourceInstance {
	if x != nil {
		return x.DataSourceInstance
	}
	return nil
}

func (x *TClientConfig) GetMetricsServerEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.MetricsServerEndpoint
	}
	return nil
}

type TClientTLSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CA certificate path
	Ca string `protobuf:"bytes,1,opt,name=ca,proto3" json:"ca,omitempty"`
	// Disables certificate host name checking.
	// Should be used carefully only for debugging purposes.
	// See https://pkg.go.dev/crypto/tls#Config for more details.
	InsecureSkipVerify bool `protobuf:"varint,2,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TClientTLSConfig) Reset() {
	*x = TClientTLSConfig{}
	mi := &file_app_config_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TClientTLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TClientTLSConfig) ProtoMessage() {}

func (x *TClientTLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TClientTLSConfig.ProtoReflect.Descriptor instead.
func (*TClientTLSConfig) Descriptor() ([]byte, []int) {
	return file_app_config_client_proto_rawDescGZIP(), []int{1}
}

func (x *TClientTLSConfig) GetCa() string {
	if x != nil {
		return x.Ca
	}
	return ""
}

func (x *TClientTLSConfig) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

var File_app_config_client_proto protoreflect.FileDescriptor

const file_app_config_client_proto_rawDesc = "" +
	"\n" +
	"\x17app/config/client.proto\x12\x19NYql.Connector.App.Config\x1a;yql/essentials/providers/common/proto/gateways_config.proto\"\xcc\x02\n" +
	"\rTClientConfig\x12R\n" +
	"\x19connector_server_endpoint\x18\x04 \x01(\v2\x16.NYql.TGenericEndpointR\x17connectorServerEndpoint\x12=\n" +
	"\x03tls\x18\x02 \x01(\v2+.NYql.Connector.App.Config.TClientTLSConfigR\x03tls\x12R\n" +
	"\x14data_source_instance\x18\x03 \x01(\v2 .NYql.TGenericDataSourceInstanceR\x12dataSourceInstance\x12N\n" +
	"\x17metrics_server_endpoint\x18\x05 \x01(\v2\x16.NYql.TGenericEndpointR\x15metricsServerEndpointJ\x04\b\x01\x10\x02\"T\n" +
	"\x10TClientTLSConfig\x12\x0e\n" +
	"\x02ca\x18\x01 \x01(\tR\x02ca\x120\n" +
	"\x14insecure_skip_verify\x18\x02 \x01(\bR\x12insecureSkipVerifyB4Z2github.com/ydb-platform/fq-connector-go/app/configb\x06proto3"

var (
	file_app_config_client_proto_rawDescOnce sync.Once
	file_app_config_client_proto_rawDescData []byte
)

func file_app_config_client_proto_rawDescGZIP() []byte {
	file_app_config_client_proto_rawDescOnce.Do(func() {
		file_app_config_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_config_client_proto_rawDesc), len(file_app_config_client_proto_rawDesc)))
	})
	return file_app_config_client_proto_rawDescData
}

var file_app_config_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_config_client_proto_goTypes = []any{
	(*TClientConfig)(nil),                     // 0: NYql.Connector.App.Config.TClientConfig
	(*TClientTLSConfig)(nil),                  // 1: NYql.Connector.App.Config.TClientTLSConfig
	(*common.TGenericEndpoint)(nil),           // 2: NYql.TGenericEndpoint
	(*common.TGenericDataSourceInstance)(nil), // 3: NYql.TGenericDataSourceInstance
}
var file_app_config_client_proto_depIdxs = []int32{
	2, // 0: NYql.Connector.App.Config.TClientConfig.connector_server_endpoint:type_name -> NYql.TGenericEndpoint
	1, // 1: NYql.Connector.App.Config.TClientConfig.tls:type_name -> NYql.Connector.App.Config.TClientTLSConfig
	3, // 2: NYql.Connector.App.Config.TClientConfig.data_source_instance:type_name -> NYql.TGenericDataSourceInstance
	2, // 3: NYql.Connector.App.Config.TClientConfig.metrics_server_endpoint:type_name -> NYql.TGenericEndpoint
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_config_client_proto_init() }
func file_app_config_client_proto_init() {
	if File_app_config_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_config_client_proto_rawDesc), len(file_app_config_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_config_client_proto_goTypes,
		DependencyIndexes: file_app_config_client_proto_depIdxs,
		MessageInfos:      file_app_config_client_proto_msgTypes,
	}.Build()
	File_app_config_client_proto = out.File
	file_app_config_client_proto_goTypes = nil
	file_app_config_client_proto_depIdxs = nil
}
