// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: app/config/server.proto

package config

import (
	common "github.com/ydb-platform/fq-connector-go/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ELogLevel enumerates standard levels of logging
type ELogLevel int32

const (
	ELogLevel_TRACE ELogLevel = 0
	ELogLevel_DEBUG ELogLevel = 1
	ELogLevel_INFO  ELogLevel = 2
	ELogLevel_WARN  ELogLevel = 3
	ELogLevel_ERROR ELogLevel = 4
	ELogLevel_FATAL ELogLevel = 5
)

// Enum value maps for ELogLevel.
var (
	ELogLevel_name = map[int32]string{
		0: "TRACE",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
		5: "FATAL",
	}
	ELogLevel_value = map[string]int32{
		"TRACE": 0,
		"DEBUG": 1,
		"INFO":  2,
		"WARN":  3,
		"ERROR": 4,
		"FATAL": 5,
	}
)

func (x ELogLevel) Enum() *ELogLevel {
	p := new(ELogLevel)
	*p = x
	return p
}

func (x ELogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ELogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_app_config_server_proto_enumTypes[0].Descriptor()
}

func (ELogLevel) Type() protoreflect.EnumType {
	return &file_app_config_server_proto_enumTypes[0]
}

func (x ELogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ELogLevel.Descriptor instead.
func (ELogLevel) EnumDescriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{0}
}

type TMongoDbConfig_EObjectIdYqlType int32

const (
	TMongoDbConfig_OBJECT_ID_UNSPECIFIED      TMongoDbConfig_EObjectIdYqlType = 0
	TMongoDbConfig_OBJECT_ID_AS_STRING        TMongoDbConfig_EObjectIdYqlType = 1
	TMongoDbConfig_OBJECT_ID_AS_TAGGED_STRING TMongoDbConfig_EObjectIdYqlType = 2
)

// Enum value maps for TMongoDbConfig_EObjectIdYqlType.
var (
	TMongoDbConfig_EObjectIdYqlType_name = map[int32]string{
		0: "OBJECT_ID_UNSPECIFIED",
		1: "OBJECT_ID_AS_STRING",
		2: "OBJECT_ID_AS_TAGGED_STRING",
	}
	TMongoDbConfig_EObjectIdYqlType_value = map[string]int32{
		"OBJECT_ID_UNSPECIFIED":      0,
		"OBJECT_ID_AS_STRING":        1,
		"OBJECT_ID_AS_TAGGED_STRING": 2,
	}
)

func (x TMongoDbConfig_EObjectIdYqlType) Enum() *TMongoDbConfig_EObjectIdYqlType {
	p := new(TMongoDbConfig_EObjectIdYqlType)
	*p = x
	return p
}

func (x TMongoDbConfig_EObjectIdYqlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TMongoDbConfig_EObjectIdYqlType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_config_server_proto_enumTypes[1].Descriptor()
}

func (TMongoDbConfig_EObjectIdYqlType) Type() protoreflect.EnumType {
	return &file_app_config_server_proto_enumTypes[1]
}

func (x TMongoDbConfig_EObjectIdYqlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TMongoDbConfig_EObjectIdYqlType.Descriptor instead.
func (TMongoDbConfig_EObjectIdYqlType) EnumDescriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{16, 0}
}

type TYdbConfig_Mode int32

const (
	TYdbConfig_MODE_UNSPECIFIED TYdbConfig_Mode = 0
	// In MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES the YDB connector uses YDB's Table Service
	// via Go's standard library database/sql interface.
	// All the requests are marked as scan queries.
	TYdbConfig_MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES TYdbConfig_Mode = 1
	// In MODE_QUERY_SERVICE_NATIVE the YDB connector uses YDB's Query Service
	// via native YDB interface.
	TYdbConfig_MODE_QUERY_SERVICE_NATIVE TYdbConfig_Mode = 2
)

// Enum value maps for TYdbConfig_Mode.
var (
	TYdbConfig_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES",
		2: "MODE_QUERY_SERVICE_NATIVE",
	}
	TYdbConfig_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":                       0,
		"MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES": 1,
		"MODE_QUERY_SERVICE_NATIVE":              2,
	}
)

func (x TYdbConfig_Mode) Enum() *TYdbConfig_Mode {
	p := new(TYdbConfig_Mode)
	*p = x
	return p
}

func (x TYdbConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYdbConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_app_config_server_proto_enumTypes[2].Descriptor()
}

func (TYdbConfig_Mode) Type() protoreflect.EnumType {
	return &file_app_config_server_proto_enumTypes[2]
}

func (x TYdbConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYdbConfig_Mode.Descriptor instead.
func (TYdbConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{20, 0}
}

// Connector server configuration
type TServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in app/config/server.proto.
	Endpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Deprecated: Marked as deprecated in app/config/server.proto.
	Tls *TServerTLSConfig `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	// TConnectorServerConfig contains configuration of the main GRPC server
	ConnectorServer *TConnectorServerConfig `protobuf:"bytes,5,opt,name=connector_server,json=connectorServer,proto3" json:"connector_server,omitempty"`
	// This is a rough restriction for YQ memory consumption until
	// https://st.yandex-team.ru/YQ-2057 is implemented.
	// Leave it empty if you want to avoid any memory limits.
	ReadLimit *TServerReadLimit `protobuf:"bytes,3,opt,name=read_limit,json=readLimit,proto3" json:"read_limit,omitempty"`
	// Logger config
	Logger *TLoggerConfig `protobuf:"bytes,4,opt,name=logger,proto3" json:"logger,omitempty"`
	// Go runtime profiler.
	// Disabled if this part of config is empty.
	PprofServer *TPprofServerConfig `protobuf:"bytes,6,opt,name=pprof_server,json=pprofServer,proto3" json:"pprof_server,omitempty"`
	// Metrics server config
	MetricsServer *TMetricsServerConfig `protobuf:"bytes,7,opt,name=metrics_server,json=metricsServer,proto3" json:"metrics_server,omitempty"`
	// Paging config
	Paging *TPagingConfig `protobuf:"bytes,8,opt,name=paging,proto3" json:"paging,omitempty"`
	// Data types conversion config
	Conversion *TConversionConfig `protobuf:"bytes,9,opt,name=conversion,proto3" json:"conversion,omitempty"`
	// Datasource-specific config
	Datasources   *TDatasourcesConfig `protobuf:"bytes,10,opt,name=datasources,proto3" json:"datasources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TServerConfig) Reset() {
	*x = TServerConfig{}
	mi := &file_app_config_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TServerConfig) ProtoMessage() {}

func (x *TServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TServerConfig.ProtoReflect.Descriptor instead.
func (*TServerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in app/config/server.proto.
func (x *TServerConfig) GetEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

// Deprecated: Marked as deprecated in app/config/server.proto.
func (x *TServerConfig) GetTls() *TServerTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *TServerConfig) GetConnectorServer() *TConnectorServerConfig {
	if x != nil {
		return x.ConnectorServer
	}
	return nil
}

func (x *TServerConfig) GetReadLimit() *TServerReadLimit {
	if x != nil {
		return x.ReadLimit
	}
	return nil
}

func (x *TServerConfig) GetLogger() *TLoggerConfig {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *TServerConfig) GetPprofServer() *TPprofServerConfig {
	if x != nil {
		return x.PprofServer
	}
	return nil
}

func (x *TServerConfig) GetMetricsServer() *TMetricsServerConfig {
	if x != nil {
		return x.MetricsServer
	}
	return nil
}

func (x *TServerConfig) GetPaging() *TPagingConfig {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *TServerConfig) GetConversion() *TConversionConfig {
	if x != nil {
		return x.Conversion
	}
	return nil
}

func (x *TServerConfig) GetDatasources() *TDatasourcesConfig {
	if x != nil {
		return x.Datasources
	}
	return nil
}

// TConnectorServerConfig - configuration of the main GRPC server
type TConnectorServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network address server will be listening on
	Endpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// TLS settings.
	// Leave it empty for insecure connections.
	Tls *TServerTLSConfig `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	// Defines maximum GRPC request size
	MaxRecvMessageSize uint64 `protobuf:"varint,3,opt,name=max_recv_message_size,json=maxRecvMessageSize,proto3" json:"max_recv_message_size,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TConnectorServerConfig) Reset() {
	*x = TConnectorServerConfig{}
	mi := &file_app_config_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TConnectorServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConnectorServerConfig) ProtoMessage() {}

func (x *TConnectorServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConnectorServerConfig.ProtoReflect.Descriptor instead.
func (*TConnectorServerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{1}
}

func (x *TConnectorServerConfig) GetEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *TConnectorServerConfig) GetTls() *TServerTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *TConnectorServerConfig) GetMaxRecvMessageSize() uint64 {
	if x != nil {
		return x.MaxRecvMessageSize
	}
	return 0
}

type TServerTLSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TLS private key path
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// TLS public cert path
	Cert          string `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TServerTLSConfig) Reset() {
	*x = TServerTLSConfig{}
	mi := &file_app_config_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TServerTLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TServerTLSConfig) ProtoMessage() {}

func (x *TServerTLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TServerTLSConfig.ProtoReflect.Descriptor instead.
func (*TServerTLSConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{2}
}

func (x *TServerTLSConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TServerTLSConfig) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

// ServerReadLimit limitates the amount of data extracted from the data source on every read request.
type TServerReadLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of rows extracted from the data source
	Rows          uint64 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TServerReadLimit) Reset() {
	*x = TServerReadLimit{}
	mi := &file_app_config_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TServerReadLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TServerReadLimit) ProtoMessage() {}

func (x *TServerReadLimit) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TServerReadLimit.ProtoReflect.Descriptor instead.
func (*TServerReadLimit) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{3}
}

func (x *TServerReadLimit) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// TLogger represents logger configuration
type TLoggerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Level of logging
	LogLevel ELogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=NYql.Connector.App.Config.ELogLevel" json:"log_level,omitempty"`
	// Is logging of queries enabled
	EnableSqlQueryLogging bool `protobuf:"varint,2,opt,name=enable_sql_query_logging,json=enableSqlQueryLogging,proto3" json:"enable_sql_query_logging,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TLoggerConfig) Reset() {
	*x = TLoggerConfig{}
	mi := &file_app_config_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggerConfig) ProtoMessage() {}

func (x *TLoggerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggerConfig.ProtoReflect.Descriptor instead.
func (*TLoggerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{4}
}

func (x *TLoggerConfig) GetLogLevel() ELogLevel {
	if x != nil {
		return x.LogLevel
	}
	return ELogLevel_TRACE
}

func (x *TLoggerConfig) GetEnableSqlQueryLogging() bool {
	if x != nil {
		return x.EnableSqlQueryLogging
	}
	return false
}

// TPprofServerConfig configures HTTP server delivering Go runtime profiler data
type TPprofServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network address server will be listening on
	Endpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// TLS settings.
	// Leave it empty for insecure connections.
	Tls           *TServerTLSConfig `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TPprofServerConfig) Reset() {
	*x = TPprofServerConfig{}
	mi := &file_app_config_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPprofServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPprofServerConfig) ProtoMessage() {}

func (x *TPprofServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPprofServerConfig.ProtoReflect.Descriptor instead.
func (*TPprofServerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{5}
}

func (x *TPprofServerConfig) GetEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *TPprofServerConfig) GetTls() *TServerTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

// TMetricsConfig - configuration of the metrics service
type TMetricsServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network address server will be listening on
	Endpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// TLS settings.
	// Leave it empty for insecure connections.
	Tls           *TServerTLSConfig `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMetricsServerConfig) Reset() {
	*x = TMetricsServerConfig{}
	mi := &file_app_config_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMetricsServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMetricsServerConfig) ProtoMessage() {}

func (x *TMetricsServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMetricsServerConfig.ProtoReflect.Descriptor instead.
func (*TMetricsServerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{6}
}

func (x *TMetricsServerConfig) GetEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *TMetricsServerConfig) GetTls() *TServerTLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

// TPagingConfig configures the way of splitting of the data stream into the fragments (or pages)
// in order to return them as separate GRPC messages to the client.
type TPagingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configures the limit of a page size in rows.
	// It may override other limits. Ignored if set to zero.
	RowsPerPage uint64 `protobuf:"varint,1,opt,name=rows_per_page,json=rowsPerPage,proto3" json:"rows_per_page,omitempty"`
	// Configures the limit of a page size in bytes.
	// It may override other limits. Ignored if set to zero.
	BytesPerPage uint64 `protobuf:"varint,2,opt,name=bytes_per_page,json=bytesPerPage,proto3" json:"bytes_per_page,omitempty"`
	// Connector service can read ahead some data from the data source before returning it to the client.
	// This setting configures the number of pages that may reside in the service's address space
	// waiting for the client readiness for the data consumption.
	// Tune this carefully cause this may cause service OOMs.
	PrefetchQueueCapacity uint32 `protobuf:"varint,3,opt,name=prefetch_queue_capacity,json=prefetchQueueCapacity,proto3" json:"prefetch_queue_capacity,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TPagingConfig) Reset() {
	*x = TPagingConfig{}
	mi := &file_app_config_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPagingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPagingConfig) ProtoMessage() {}

func (x *TPagingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPagingConfig.ProtoReflect.Descriptor instead.
func (*TPagingConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{7}
}

func (x *TPagingConfig) GetRowsPerPage() uint64 {
	if x != nil {
		return x.RowsPerPage
	}
	return 0
}

func (x *TPagingConfig) GetBytesPerPage() uint64 {
	if x != nil {
		return x.BytesPerPage
	}
	return 0
}

func (x *TPagingConfig) GetPrefetchQueueCapacity() uint32 {
	if x != nil {
		return x.PrefetchQueueCapacity
	}
	return 0
}

// TConversionConfig configures some aspects of the data conversion process
// between the data source native type system, Go type system and Arrow type system
type TConversionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enables microoptimized code that can potentially crash the service
	UseUnsafeConverters bool `protobuf:"varint,1,opt,name=use_unsafe_converters,json=useUnsafeConverters,proto3" json:"use_unsafe_converters,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TConversionConfig) Reset() {
	*x = TConversionConfig{}
	mi := &file_app_config_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TConversionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TConversionConfig) ProtoMessage() {}

func (x *TConversionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TConversionConfig.ProtoReflect.Descriptor instead.
func (*TConversionConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{8}
}

func (x *TConversionConfig) GetUseUnsafeConverters() bool {
	if x != nil {
		return x.UseUnsafeConverters
	}
	return false
}

// TExponentialBackoffConfig provides configuration for the exponential backoff
// which is used for retries of the operations ended up with transient errors.
type TExponentialBackoffConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial interval between retries
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	InitialInterval string `protobuf:"bytes,1,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"`
	// Maximum total time for retries
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	MaxInterval string `protobuf:"bytes,2,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	// Randomization factor to add jitter to intervals
	RandomizationFactor float64 `protobuf:"fixed64,3,opt,name=randomization_factor,json=randomizationFactor,proto3" json:"randomization_factor,omitempty"`
	// Multiplier for increasing the interval after each retry
	Multiplier float64 `protobuf:"fixed64,4,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	// Maximum interval between retries
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	MaxElapsedTime string `protobuf:"bytes,5,opt,name=max_elapsed_time,json=maxElapsedTime,proto3" json:"max_elapsed_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TExponentialBackoffConfig) Reset() {
	*x = TExponentialBackoffConfig{}
	mi := &file_app_config_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TExponentialBackoffConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TExponentialBackoffConfig) ProtoMessage() {}

func (x *TExponentialBackoffConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TExponentialBackoffConfig.ProtoReflect.Descriptor instead.
func (*TExponentialBackoffConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{9}
}

func (x *TExponentialBackoffConfig) GetInitialInterval() string {
	if x != nil {
		return x.InitialInterval
	}
	return ""
}

func (x *TExponentialBackoffConfig) GetMaxInterval() string {
	if x != nil {
		return x.MaxInterval
	}
	return ""
}

func (x *TExponentialBackoffConfig) GetRandomizationFactor() float64 {
	if x != nil {
		return x.RandomizationFactor
	}
	return 0
}

func (x *TExponentialBackoffConfig) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *TExponentialBackoffConfig) GetMaxElapsedTime() string {
	if x != nil {
		return x.MaxElapsedTime
	}
	return ""
}

// TPushdownConfig contains various settings for predicate pushdown
type TPushdownConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enables filter pushdown for columns of YQL Timestamp type
	EnableTimestampPushdown bool `protobuf:"varint,1,opt,name=enable_timestamp_pushdown,json=enableTimestampPushdown,proto3" json:"enable_timestamp_pushdown,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TPushdownConfig) Reset() {
	*x = TPushdownConfig{}
	mi := &file_app_config_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPushdownConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPushdownConfig) ProtoMessage() {}

func (x *TPushdownConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPushdownConfig.ProtoReflect.Descriptor instead.
func (*TPushdownConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{10}
}

func (x *TPushdownConfig) GetEnableTimestampPushdown() bool {
	if x != nil {
		return x.EnableTimestampPushdown
	}
	return false
}

// TClickHouseConfig contains settings specific for ClickHouse data source
type TClickHouseConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for ClickHouse connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	// Timeout for ClickHouse connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string                     `protobuf:"bytes,2,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TClickHouseConfig) Reset() {
	*x = TClickHouseConfig{}
	mi := &file_app_config_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TClickHouseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TClickHouseConfig) ProtoMessage() {}

func (x *TClickHouseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TClickHouseConfig.ProtoReflect.Descriptor instead.
func (*TClickHouseConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{11}
}

func (x *TClickHouseConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TClickHouseConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TClickHouseConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TClickHouseConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TGreenplumConfig contains settings specific for Greenplum data source
type TGreenplumConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for Greenplum connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string                     `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TGreenplumConfig) Reset() {
	*x = TGreenplumConfig{}
	mi := &file_app_config_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TGreenplumConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TGreenplumConfig) ProtoMessage() {}

func (x *TGreenplumConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TGreenplumConfig.ProtoReflect.Descriptor instead.
func (*TGreenplumConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{12}
}

func (x *TGreenplumConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TGreenplumConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TGreenplumConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TMsSQLServerConfig contains settings specific for MsSQLServer data source
type TMsSQLServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for ClickHouse connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string `protobuf:"bytes,2,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	// Timeout for MsSQLServer connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string                     `protobuf:"bytes,1,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TMsSQLServerConfig) Reset() {
	*x = TMsSQLServerConfig{}
	mi := &file_app_config_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMsSQLServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMsSQLServerConfig) ProtoMessage() {}

func (x *TMsSQLServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMsSQLServerConfig.ProtoReflect.Descriptor instead.
func (*TMsSQLServerConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{13}
}

func (x *TMsSQLServerConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TMsSQLServerConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TMsSQLServerConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TMsSQLServerConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

type TMySQLConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResultChanCapacity uint64                 `protobuf:"varint,1,opt,name=result_chan_capacity,json=resultChanCapacity,proto3" json:"result_chan_capacity,omitempty"`
	// Timeout for MySQL connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string                     `protobuf:"bytes,2,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TMySQLConfig) Reset() {
	*x = TMySQLConfig{}
	mi := &file_app_config_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMySQLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMySQLConfig) ProtoMessage() {}

func (x *TMySQLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMySQLConfig.ProtoReflect.Descriptor instead.
func (*TMySQLConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{14}
}

func (x *TMySQLConfig) GetResultChanCapacity() uint64 {
	if x != nil {
		return x.ResultChanCapacity
	}
	return 0
}

func (x *TMySQLConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TMySQLConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TMySQLConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TOracleConfig contains settings specific for Oracle data source
type TOracleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for Oracle connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	// Timeout for Oracle connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string                     `protobuf:"bytes,2,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TOracleConfig) Reset() {
	*x = TOracleConfig{}
	mi := &file_app_config_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOracleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOracleConfig) ProtoMessage() {}

func (x *TOracleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOracleConfig.ProtoReflect.Descriptor instead.
func (*TOracleConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{15}
}

func (x *TOracleConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TOracleConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TOracleConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TOracleConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TMongoDbConfig contains settings specific for MongoDB data source
type TMongoDbConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for MongoDB connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	// Timeout for MongoDB connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string `protobuf:"bytes,2,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	// Number of documents to process in DescribeTable method to deduce table schema
	CountDocsToDeduceSchema uint32 `protobuf:"varint,3,opt,name=count_docs_to_deduce_schema,json=countDocsToDeduceSchema,proto3" json:"count_docs_to_deduce_schema,omitempty"`
	// YQL Type to use for representing ObjectId
	ObjectIdYqlType    TMongoDbConfig_EObjectIdYqlType `protobuf:"varint,4,opt,name=object_id_yql_type,json=objectIdYqlType,proto3,enum=NYql.Connector.App.Config.TMongoDbConfig_EObjectIdYqlType" json:"object_id_yql_type,omitempty"`
	ExponentialBackoff *TExponentialBackoffConfig      `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TMongoDbConfig) Reset() {
	*x = TMongoDbConfig{}
	mi := &file_app_config_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMongoDbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMongoDbConfig) ProtoMessage() {}

func (x *TMongoDbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMongoDbConfig.ProtoReflect.Descriptor instead.
func (*TMongoDbConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{16}
}

func (x *TMongoDbConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TMongoDbConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TMongoDbConfig) GetCountDocsToDeduceSchema() uint32 {
	if x != nil {
		return x.CountDocsToDeduceSchema
	}
	return 0
}

func (x *TMongoDbConfig) GetObjectIdYqlType() TMongoDbConfig_EObjectIdYqlType {
	if x != nil {
		return x.ObjectIdYqlType
	}
	return TMongoDbConfig_OBJECT_ID_UNSPECIFIED
}

func (x *TMongoDbConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

// TRedisConfig contains settings specific for Redis data source
type TRedisConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for Redis connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string `protobuf:"bytes,2,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	// Number of values to process in DescribeTable method to deduce table schema
	CountDocsToDeduceSchema uint32                     `protobuf:"varint,3,opt,name=count_docs_to_deduce_schema,json=countDocsToDeduceSchema,proto3" json:"count_docs_to_deduce_schema,omitempty"`
	ExponentialBackoff      *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TRedisConfig) Reset() {
	*x = TRedisConfig{}
	mi := &file_app_config_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TRedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRedisConfig) ProtoMessage() {}

func (x *TRedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRedisConfig.ProtoReflect.Descriptor instead.
func (*TRedisConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{17}
}

func (x *TRedisConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TRedisConfig) GetCountDocsToDeduceSchema() uint32 {
	if x != nil {
		return x.CountDocsToDeduceSchema
	}
	return 0
}

func (x *TRedisConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

// TOpenSearchConfig contains settings specific for OpenSearch data source
type TOpenSearchConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for establishing a connection to OpenSearch
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	DialTimeout string `protobuf:"bytes,1,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	// Timeout for waiting for response headers from OpenSearch
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	ResponseHeaderTimeout string `protobuf:"bytes,2,opt,name=response_header_timeout,json=responseHeaderTimeout,proto3" json:"response_header_timeout,omitempty"`
	// Timeout for pinging the OpenSearch server to check connectivity
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string                     `protobuf:"bytes,3,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TOpenSearchConfig) Reset() {
	*x = TOpenSearchConfig{}
	mi := &file_app_config_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TOpenSearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TOpenSearchConfig) ProtoMessage() {}

func (x *TOpenSearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TOpenSearchConfig.ProtoReflect.Descriptor instead.
func (*TOpenSearchConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{18}
}

func (x *TOpenSearchConfig) GetDialTimeout() string {
	if x != nil {
		return x.DialTimeout
	}
	return ""
}

func (x *TOpenSearchConfig) GetResponseHeaderTimeout() string {
	if x != nil {
		return x.ResponseHeaderTimeout
	}
	return ""
}

func (x *TOpenSearchConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TOpenSearchConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

// TPostgreSQLConfig contains settings specific for PostgreSQL data source
type TPostgreSQLConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for PostgreSQL connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string                     `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	ExponentialBackoff    *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown              *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TPostgreSQLConfig) Reset() {
	*x = TPostgreSQLConfig{}
	mi := &file_app_config_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPostgreSQLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPostgreSQLConfig) ProtoMessage() {}

func (x *TPostgreSQLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPostgreSQLConfig.ProtoReflect.Descriptor instead.
func (*TPostgreSQLConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{19}
}

func (x *TPostgreSQLConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TPostgreSQLConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TPostgreSQLConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TYdbConfig contains settings specific for YDB data source
type TYdbConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timeout for YDB connection opening.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	OpenConnectionTimeout string `protobuf:"bytes,1,opt,name=open_connection_timeout,json=openConnectionTimeout,proto3" json:"open_connection_timeout,omitempty"`
	// Timeout for YDB connection pinging.
	// Valid values should satisfy `time.ParseDuration` (e. g. '5s', '100ms', '3h').
	PingConnectionTimeout string `protobuf:"bytes,2,opt,name=ping_connection_timeout,json=pingConnectionTimeout,proto3" json:"ping_connection_timeout,omitempty"`
	// Flag forcing the usage of underlay networks for dedicated YDB databases
	UseUnderlayNetworkForDedicatedDatabases bool `protobuf:"varint,3,opt,name=use_underlay_network_for_dedicated_databases,json=useUnderlayNetworkForDedicatedDatabases,proto3" json:"use_underlay_network_for_dedicated_databases,omitempty"`
	// Mode parametrizes the way YDB connector interacts with YDB servers.
	// MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES is the default mode.
	Mode TYdbConfig_Mode `protobuf:"varint,4,opt,name=mode,proto3,enum=NYql.Connector.App.Config.TYdbConfig_Mode" json:"mode,omitempty"`
	// Path to JSON file with static SA credentials.
	// If this file is provided, the YDB connector will use
	// this credentials to access the database.
	ServiceAccountKeyFileCredentials string `protobuf:"bytes,5,opt,name=service_account_key_file_credentials,json=serviceAccountKeyFileCredentials,proto3" json:"service_account_key_file_credentials,omitempty"`
	// One should provide IAM endpoint to authenticate service account
	// if service_account_key_file_credentials is set.
	IamEndpoint        *common.TGenericEndpoint   `protobuf:"bytes,6,opt,name=iam_endpoint,json=iamEndpoint,proto3" json:"iam_endpoint,omitempty"`
	Splitting          *TYdbConfig_TSplitting     `protobuf:"bytes,7,opt,name=splitting,proto3" json:"splitting,omitempty"`
	ExponentialBackoff *TExponentialBackoffConfig `protobuf:"bytes,10,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	Pushdown           *TPushdownConfig           `protobuf:"bytes,11,opt,name=pushdown,proto3" json:"pushdown,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TYdbConfig) Reset() {
	*x = TYdbConfig{}
	mi := &file_app_config_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TYdbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TYdbConfig) ProtoMessage() {}

func (x *TYdbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TYdbConfig.ProtoReflect.Descriptor instead.
func (*TYdbConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{20}
}

func (x *TYdbConfig) GetOpenConnectionTimeout() string {
	if x != nil {
		return x.OpenConnectionTimeout
	}
	return ""
}

func (x *TYdbConfig) GetPingConnectionTimeout() string {
	if x != nil {
		return x.PingConnectionTimeout
	}
	return ""
}

func (x *TYdbConfig) GetUseUnderlayNetworkForDedicatedDatabases() bool {
	if x != nil {
		return x.UseUnderlayNetworkForDedicatedDatabases
	}
	return false
}

func (x *TYdbConfig) GetMode() TYdbConfig_Mode {
	if x != nil {
		return x.Mode
	}
	return TYdbConfig_MODE_UNSPECIFIED
}

func (x *TYdbConfig) GetServiceAccountKeyFileCredentials() string {
	if x != nil {
		return x.ServiceAccountKeyFileCredentials
	}
	return ""
}

func (x *TYdbConfig) GetIamEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.IamEndpoint
	}
	return nil
}

func (x *TYdbConfig) GetSplitting() *TYdbConfig_TSplitting {
	if x != nil {
		return x.Splitting
	}
	return nil
}

func (x *TYdbConfig) GetExponentialBackoff() *TExponentialBackoffConfig {
	if x != nil {
		return x.ExponentialBackoff
	}
	return nil
}

func (x *TYdbConfig) GetPushdown() *TPushdownConfig {
	if x != nil {
		return x.Pushdown
	}
	return nil
}

// TLoggingConfig contains settings specific for Logging external datasource
type TLoggingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Under the hood the Logging connector goes to YDB,
	// so all YDB settings can be applied to this connector as well.
	Ydb *TYdbConfig `protobuf:"bytes,1,opt,name=ydb,proto3" json:"ydb,omitempty"`
	// Types that are valid to be assigned to Resolving:
	//
	//	*TLoggingConfig_Dynamic
	//	*TLoggingConfig_Static
	Resolving     isTLoggingConfig_Resolving `protobuf_oneof:"resolving"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLoggingConfig) Reset() {
	*x = TLoggingConfig{}
	mi := &file_app_config_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggingConfig) ProtoMessage() {}

func (x *TLoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggingConfig.ProtoReflect.Descriptor instead.
func (*TLoggingConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{21}
}

func (x *TLoggingConfig) GetYdb() *TYdbConfig {
	if x != nil {
		return x.Ydb
	}
	return nil
}

func (x *TLoggingConfig) GetResolving() isTLoggingConfig_Resolving {
	if x != nil {
		return x.Resolving
	}
	return nil
}

func (x *TLoggingConfig) GetDynamic() *TLoggingConfig_TDynamicResolving {
	if x != nil {
		if x, ok := x.Resolving.(*TLoggingConfig_Dynamic); ok {
			return x.Dynamic
		}
	}
	return nil
}

func (x *TLoggingConfig) GetStatic() *TLoggingConfig_TStaticResolving {
	if x != nil {
		if x, ok := x.Resolving.(*TLoggingConfig_Static); ok {
			return x.Static
		}
	}
	return nil
}

type isTLoggingConfig_Resolving interface {
	isTLoggingConfig_Resolving()
}

type TLoggingConfig_Dynamic struct {
	Dynamic *TLoggingConfig_TDynamicResolving `protobuf:"bytes,2,opt,name=dynamic,proto3,oneof"`
}

type TLoggingConfig_Static struct {
	Static *TLoggingConfig_TStaticResolving `protobuf:"bytes,3,opt,name=static,proto3,oneof"`
}

func (*TLoggingConfig_Dynamic) isTLoggingConfig_Resolving() {}

func (*TLoggingConfig_Static) isTLoggingConfig_Resolving() {}

// TDatasouceConfig is a collection of datasource-specific settings
type TDatasourcesConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ydb           *TYdbConfig            `protobuf:"bytes,1,opt,name=ydb,proto3" json:"ydb,omitempty"`
	Mysql         *TMySQLConfig          `protobuf:"bytes,2,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Clickhouse    *TClickHouseConfig     `protobuf:"bytes,3,opt,name=clickhouse,proto3" json:"clickhouse,omitempty"`
	MsSqlServer   *TMsSQLServerConfig    `protobuf:"bytes,4,opt,name=ms_sql_server,json=msSqlServer,proto3" json:"ms_sql_server,omitempty"`
	Postgresql    *TPostgreSQLConfig     `protobuf:"bytes,5,opt,name=postgresql,proto3" json:"postgresql,omitempty"`
	Greenplum     *TGreenplumConfig      `protobuf:"bytes,6,opt,name=greenplum,proto3" json:"greenplum,omitempty"`
	Oracle        *TOracleConfig         `protobuf:"bytes,7,opt,name=oracle,proto3" json:"oracle,omitempty"`
	Logging       *TLoggingConfig        `protobuf:"bytes,8,opt,name=logging,proto3" json:"logging,omitempty"`
	Mongodb       *TMongoDbConfig        `protobuf:"bytes,9,opt,name=mongodb,proto3" json:"mongodb,omitempty"`
	Redis         *TRedisConfig          `protobuf:"bytes,10,opt,name=redis,proto3" json:"redis,omitempty"`
	Opensearch    *TOpenSearchConfig     `protobuf:"bytes,11,opt,name=opensearch,proto3" json:"opensearch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TDatasourcesConfig) Reset() {
	*x = TDatasourcesConfig{}
	mi := &file_app_config_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TDatasourcesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TDatasourcesConfig) ProtoMessage() {}

func (x *TDatasourcesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TDatasourcesConfig.ProtoReflect.Descriptor instead.
func (*TDatasourcesConfig) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{22}
}

func (x *TDatasourcesConfig) GetYdb() *TYdbConfig {
	if x != nil {
		return x.Ydb
	}
	return nil
}

func (x *TDatasourcesConfig) GetMysql() *TMySQLConfig {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *TDatasourcesConfig) GetClickhouse() *TClickHouseConfig {
	if x != nil {
		return x.Clickhouse
	}
	return nil
}

func (x *TDatasourcesConfig) GetMsSqlServer() *TMsSQLServerConfig {
	if x != nil {
		return x.MsSqlServer
	}
	return nil
}

func (x *TDatasourcesConfig) GetPostgresql() *TPostgreSQLConfig {
	if x != nil {
		return x.Postgresql
	}
	return nil
}

func (x *TDatasourcesConfig) GetGreenplum() *TGreenplumConfig {
	if x != nil {
		return x.Greenplum
	}
	return nil
}

func (x *TDatasourcesConfig) GetOracle() *TOracleConfig {
	if x != nil {
		return x.Oracle
	}
	return nil
}

func (x *TDatasourcesConfig) GetLogging() *TLoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *TDatasourcesConfig) GetMongodb() *TMongoDbConfig {
	if x != nil {
		return x.Mongodb
	}
	return nil
}

func (x *TDatasourcesConfig) GetRedis() *TRedisConfig {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *TDatasourcesConfig) GetOpensearch() *TOpenSearchConfig {
	if x != nil {
		return x.Opensearch
	}
	return nil
}

// TSplitting contains various setting for the process of table splitting
type TYdbConfig_TSplitting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enables splitting for OLAP tables
	EnabledOnColumnShards bool `protobuf:"varint,1,opt,name=enabled_on_column_shards,json=enabledOnColumnShards,proto3" json:"enabled_on_column_shards,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TYdbConfig_TSplitting) Reset() {
	*x = TYdbConfig_TSplitting{}
	mi := &file_app_config_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TYdbConfig_TSplitting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TYdbConfig_TSplitting) ProtoMessage() {}

func (x *TYdbConfig_TSplitting) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TYdbConfig_TSplitting.ProtoReflect.Descriptor instead.
func (*TYdbConfig_TSplitting) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{20, 0}
}

func (x *TYdbConfig_TSplitting) GetEnabledOnColumnShards() bool {
	if x != nil {
		return x.EnabledOnColumnShards
	}
	return false
}

// Logging connector can resolve the underlying YDB endpoints
// via calls to Cloud Logging API
type TLoggingConfig_TDynamicResolving struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	LoggingEndpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=logging_endpoint,json=loggingEndpoint,proto3" json:"logging_endpoint,omitempty"`
	// List of the databases that will be ignored in the Cloud Logging API response.
	// No data will be returned from these databases.
	DatabaseBlacklist []string `protobuf:"bytes,2,rep,name=database_blacklist,json=databaseBlacklist,proto3" json:"database_blacklist,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TLoggingConfig_TDynamicResolving) Reset() {
	*x = TLoggingConfig_TDynamicResolving{}
	mi := &file_app_config_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggingConfig_TDynamicResolving) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggingConfig_TDynamicResolving) ProtoMessage() {}

func (x *TLoggingConfig_TDynamicResolving) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggingConfig_TDynamicResolving.ProtoReflect.Descriptor instead.
func (*TLoggingConfig_TDynamicResolving) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{21, 0}
}

func (x *TLoggingConfig_TDynamicResolving) GetLoggingEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.LoggingEndpoint
	}
	return nil
}

func (x *TLoggingConfig_TDynamicResolving) GetDatabaseBlacklist() []string {
	if x != nil {
		return x.DatabaseBlacklist
	}
	return nil
}

// But for the tests it is useful to set all the YDB endpoints manually.
type TLoggingConfig_TStaticResolving struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The connector will iterate through this list while making the connections.
	Databases []*TLoggingConfig_TStaticResolving_TDatabase `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	// folder_id -> log_group_name -> log_group_id mapping is
	// used for YDB table names construction.
	Folders map[string]*TLoggingConfig_TStaticResolving_TFolder `protobuf:"bytes,2,rep,name=folders,proto3" json:"folders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Template that will be used to construct YDB table names
	// in the format Go `text/template` format, for example:
	// "logs/origin/{{.CloudName}}/{{.FolderID}}/{{.LogGroupID}}"
	TableNamingPattern string `protobuf:"bytes,3,opt,name=table_naming_pattern,json=tableNamingPattern,proto3" json:"table_naming_pattern,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TLoggingConfig_TStaticResolving) Reset() {
	*x = TLoggingConfig_TStaticResolving{}
	mi := &file_app_config_server_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggingConfig_TStaticResolving) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggingConfig_TStaticResolving) ProtoMessage() {}

func (x *TLoggingConfig_TStaticResolving) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggingConfig_TStaticResolving.ProtoReflect.Descriptor instead.
func (*TLoggingConfig_TStaticResolving) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{21, 1}
}

func (x *TLoggingConfig_TStaticResolving) GetDatabases() []*TLoggingConfig_TStaticResolving_TDatabase {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *TLoggingConfig_TStaticResolving) GetFolders() map[string]*TLoggingConfig_TStaticResolving_TFolder {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *TLoggingConfig_TStaticResolving) GetTableNamingPattern() string {
	if x != nil {
		return x.TableNamingPattern
	}
	return ""
}

type TLoggingConfig_TStaticResolving_TDatabase struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network address
	Endpoint *common.TGenericEndpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// database name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLoggingConfig_TStaticResolving_TDatabase) Reset() {
	*x = TLoggingConfig_TStaticResolving_TDatabase{}
	mi := &file_app_config_server_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggingConfig_TStaticResolving_TDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggingConfig_TStaticResolving_TDatabase) ProtoMessage() {}

func (x *TLoggingConfig_TStaticResolving_TDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggingConfig_TStaticResolving_TDatabase.ProtoReflect.Descriptor instead.
func (*TLoggingConfig_TStaticResolving_TDatabase) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{21, 1, 0}
}

func (x *TLoggingConfig_TStaticResolving_TDatabase) GetEndpoint() *common.TGenericEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *TLoggingConfig_TStaticResolving_TDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TLoggingConfig_TStaticResolving_TFolder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// log_group_name -> log_group_id mapping is
	// used for YDB table names construction.
	LogGroups map[string]string `protobuf:"bytes,1,rep,name=log_groups,json=logGroups,proto3" json:"log_groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// folders are globally unique across the cloud,
	// so we can unambiguously identify the cloud for a certain folder_id.
	CloudName     string `protobuf:"bytes,2,opt,name=cloud_name,json=cloudName,proto3" json:"cloud_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLoggingConfig_TStaticResolving_TFolder) Reset() {
	*x = TLoggingConfig_TStaticResolving_TFolder{}
	mi := &file_app_config_server_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLoggingConfig_TStaticResolving_TFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLoggingConfig_TStaticResolving_TFolder) ProtoMessage() {}

func (x *TLoggingConfig_TStaticResolving_TFolder) ProtoReflect() protoreflect.Message {
	mi := &file_app_config_server_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLoggingConfig_TStaticResolving_TFolder.ProtoReflect.Descriptor instead.
func (*TLoggingConfig_TStaticResolving_TFolder) Descriptor() ([]byte, []int) {
	return file_app_config_server_proto_rawDescGZIP(), []int{21, 1, 1}
}

func (x *TLoggingConfig_TStaticResolving_TFolder) GetLogGroups() map[string]string {
	if x != nil {
		return x.LogGroups
	}
	return nil
}

func (x *TLoggingConfig_TStaticResolving_TFolder) GetCloudName() string {
	if x != nil {
		return x.CloudName
	}
	return ""
}

var File_app_config_server_proto protoreflect.FileDescriptor

const file_app_config_server_proto_rawDesc = "" +
	"\n" +
	"\x17app/config/server.proto\x12\x19NYql.Connector.App.Config\x1a;yql/essentials/providers/common/proto/gateways_config.proto\"\x81\x06\n" +
	"\rTServerConfig\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointB\x02\x18\x01R\bendpoint\x12A\n" +
	"\x03tls\x18\x02 \x01(\v2+.NYql.Connector.App.Config.TServerTLSConfigB\x02\x18\x01R\x03tls\x12\\\n" +
	"\x10connector_server\x18\x05 \x01(\v21.NYql.Connector.App.Config.TConnectorServerConfigR\x0fconnectorServer\x12J\n" +
	"\n" +
	"read_limit\x18\x03 \x01(\v2+.NYql.Connector.App.Config.TServerReadLimitR\treadLimit\x12@\n" +
	"\x06logger\x18\x04 \x01(\v2(.NYql.Connector.App.Config.TLoggerConfigR\x06logger\x12P\n" +
	"\fpprof_server\x18\x06 \x01(\v2-.NYql.Connector.App.Config.TPprofServerConfigR\vpprofServer\x12V\n" +
	"\x0emetrics_server\x18\a \x01(\v2/.NYql.Connector.App.Config.TMetricsServerConfigR\rmetricsServer\x12@\n" +
	"\x06paging\x18\b \x01(\v2(.NYql.Connector.App.Config.TPagingConfigR\x06paging\x12L\n" +
	"\n" +
	"conversion\x18\t \x01(\v2,.NYql.Connector.App.Config.TConversionConfigR\n" +
	"conversion\x12O\n" +
	"\vdatasources\x18\n" +
	" \x01(\v2-.NYql.Connector.App.Config.TDatasourcesConfigR\vdatasources\"\xbe\x01\n" +
	"\x16TConnectorServerConfig\x122\n" +
	"\bendpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointR\bendpoint\x12=\n" +
	"\x03tls\x18\x02 \x01(\v2+.NYql.Connector.App.Config.TServerTLSConfigR\x03tls\x121\n" +
	"\x15max_recv_message_size\x18\x03 \x01(\x04R\x12maxRecvMessageSize\">\n" +
	"\x10TServerTLSConfig\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04certJ\x04\b\x01\x10\x02\"&\n" +
	"\x10TServerReadLimit\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x04R\x04rows\"\x8b\x01\n" +
	"\rTLoggerConfig\x12A\n" +
	"\tlog_level\x18\x01 \x01(\x0e2$.NYql.Connector.App.Config.ELogLevelR\blogLevel\x127\n" +
	"\x18enable_sql_query_logging\x18\x02 \x01(\bR\x15enableSqlQueryLogging\"\x87\x01\n" +
	"\x12TPprofServerConfig\x122\n" +
	"\bendpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointR\bendpoint\x12=\n" +
	"\x03tls\x18\x02 \x01(\v2+.NYql.Connector.App.Config.TServerTLSConfigR\x03tls\"\x89\x01\n" +
	"\x14TMetricsServerConfig\x122\n" +
	"\bendpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointR\bendpoint\x12=\n" +
	"\x03tls\x18\x02 \x01(\v2+.NYql.Connector.App.Config.TServerTLSConfigR\x03tls\"\x91\x01\n" +
	"\rTPagingConfig\x12\"\n" +
	"\rrows_per_page\x18\x01 \x01(\x04R\vrowsPerPage\x12$\n" +
	"\x0ebytes_per_page\x18\x02 \x01(\x04R\fbytesPerPage\x126\n" +
	"\x17prefetch_queue_capacity\x18\x03 \x01(\rR\x15prefetchQueueCapacity\"G\n" +
	"\x11TConversionConfig\x122\n" +
	"\x15use_unsafe_converters\x18\x01 \x01(\bR\x13useUnsafeConverters\"\xe6\x01\n" +
	"\x19TExponentialBackoffConfig\x12)\n" +
	"\x10initial_interval\x18\x01 \x01(\tR\x0finitialInterval\x12!\n" +
	"\fmax_interval\x18\x02 \x01(\tR\vmaxInterval\x121\n" +
	"\x14randomization_factor\x18\x03 \x01(\x01R\x13randomizationFactor\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x01R\n" +
	"multiplier\x12(\n" +
	"\x10max_elapsed_time\x18\x05 \x01(\tR\x0emaxElapsedTime\"M\n" +
	"\x0fTPushdownConfig\x12:\n" +
	"\x19enable_timestamp_pushdown\x18\x01 \x01(\bR\x17enableTimestampPushdown\"\xb2\x02\n" +
	"\x11TClickHouseConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x02 \x01(\tR\x15pingConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xf9\x01\n" +
	"\x10TGreenplumConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xb3\x02\n" +
	"\x12TMsSQLServerConfig\x126\n" +
	"\x17open_connection_timeout\x18\x02 \x01(\tR\x15openConnectionTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x01 \x01(\tR\x15pingConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xa7\x02\n" +
	"\fTMySQLConfig\x120\n" +
	"\x14result_chan_capacity\x18\x01 \x01(\x04R\x12resultChanCapacity\x126\n" +
	"\x17open_connection_timeout\x18\x02 \x01(\tR\x15openConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xae\x02\n" +
	"\rTOracleConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x02 \x01(\tR\x15pingConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xf6\x03\n" +
	"\x0eTMongoDbConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x02 \x01(\tR\x15pingConnectionTimeout\x12<\n" +
	"\x1bcount_docs_to_deduce_schema\x18\x03 \x01(\rR\x17countDocsToDeduceSchema\x12g\n" +
	"\x12object_id_yql_type\x18\x04 \x01(\x0e2:.NYql.Connector.App.Config.TMongoDbConfig.EObjectIdYqlTypeR\x0fobjectIdYqlType\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\"f\n" +
	"\x10EObjectIdYqlType\x12\x19\n" +
	"\x15OBJECT_ID_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OBJECT_ID_AS_STRING\x10\x01\x12\x1e\n" +
	"\x1aOBJECT_ID_AS_TAGGED_STRING\x10\x02\"\xeb\x01\n" +
	"\fTRedisConfig\x126\n" +
	"\x17ping_connection_timeout\x18\x02 \x01(\tR\x15pingConnectionTimeout\x12<\n" +
	"\x1bcount_docs_to_deduce_schema\x18\x03 \x01(\rR\x17countDocsToDeduceSchema\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\"\x8d\x02\n" +
	"\x11TOpenSearchConfig\x12!\n" +
	"\fdial_timeout\x18\x01 \x01(\tR\vdialTimeout\x126\n" +
	"\x17response_header_timeout\x18\x02 \x01(\tR\x15responseHeaderTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x03 \x01(\tR\x15pingConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\"\xfa\x01\n" +
	"\x11TPostgreSQLConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\"\xd5\x06\n" +
	"\n" +
	"TYdbConfig\x126\n" +
	"\x17open_connection_timeout\x18\x01 \x01(\tR\x15openConnectionTimeout\x126\n" +
	"\x17ping_connection_timeout\x18\x02 \x01(\tR\x15pingConnectionTimeout\x12]\n" +
	",use_underlay_network_for_dedicated_databases\x18\x03 \x01(\bR'useUnderlayNetworkForDedicatedDatabases\x12>\n" +
	"\x04mode\x18\x04 \x01(\x0e2*.NYql.Connector.App.Config.TYdbConfig.ModeR\x04mode\x12N\n" +
	"$service_account_key_file_credentials\x18\x05 \x01(\tR serviceAccountKeyFileCredentials\x129\n" +
	"\fiam_endpoint\x18\x06 \x01(\v2\x16.NYql.TGenericEndpointR\viamEndpoint\x12N\n" +
	"\tsplitting\x18\a \x01(\v20.NYql.Connector.App.Config.TYdbConfig.TSplittingR\tsplitting\x12e\n" +
	"\x13exponential_backoff\x18\n" +
	" \x01(\v24.NYql.Connector.App.Config.TExponentialBackoffConfigR\x12exponentialBackoff\x12F\n" +
	"\bpushdown\x18\v \x01(\v2*.NYql.Connector.App.Config.TPushdownConfigR\bpushdown\x1aE\n" +
	"\n" +
	"TSplitting\x127\n" +
	"\x18enabled_on_column_shards\x18\x01 \x01(\bR\x15enabledOnColumnShards\"g\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12*\n" +
	"&MODE_TABLE_SERVICE_STDLIB_SCAN_QUERIES\x10\x01\x12\x1d\n" +
	"\x19MODE_QUERY_SERVICE_NATIVE\x10\x02\"\xcb\b\n" +
	"\x0eTLoggingConfig\x127\n" +
	"\x03ydb\x18\x01 \x01(\v2%.NYql.Connector.App.Config.TYdbConfigR\x03ydb\x12W\n" +
	"\adynamic\x18\x02 \x01(\v2;.NYql.Connector.App.Config.TLoggingConfig.TDynamicResolvingH\x00R\adynamic\x12T\n" +
	"\x06static\x18\x03 \x01(\v2:.NYql.Connector.App.Config.TLoggingConfig.TStaticResolvingH\x00R\x06static\x1a\x85\x01\n" +
	"\x11TDynamicResolving\x12A\n" +
	"\x10logging_endpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointR\x0floggingEndpoint\x12-\n" +
	"\x12database_blacklist\x18\x02 \x03(\tR\x11databaseBlacklist\x1a\xbb\x05\n" +
	"\x10TStaticResolving\x12b\n" +
	"\tdatabases\x18\x01 \x03(\v2D.NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TDatabaseR\tdatabases\x12a\n" +
	"\afolders\x18\x02 \x03(\v2G.NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.FoldersEntryR\afolders\x120\n" +
	"\x14table_naming_pattern\x18\x03 \x01(\tR\x12tableNamingPattern\x1aS\n" +
	"\tTDatabase\x122\n" +
	"\bendpoint\x18\x01 \x01(\v2\x16.NYql.TGenericEndpointR\bendpoint\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x1a\xd8\x01\n" +
	"\aTFolder\x12p\n" +
	"\n" +
	"log_groups\x18\x01 \x03(\v2Q.NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder.LogGroupsEntryR\tlogGroups\x12\x1d\n" +
	"\n" +
	"cloud_name\x18\x02 \x01(\tR\tcloudName\x1a<\n" +
	"\x0eLogGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a~\n" +
	"\fFoldersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12X\n" +
	"\x05value\x18\x02 \x01(\v2B.NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolderR\x05value:\x028\x01B\v\n" +
	"\tresolving\"\x9f\x06\n" +
	"\x12TDatasourcesConfig\x127\n" +
	"\x03ydb\x18\x01 \x01(\v2%.NYql.Connector.App.Config.TYdbConfigR\x03ydb\x12=\n" +
	"\x05mysql\x18\x02 \x01(\v2'.NYql.Connector.App.Config.TMySQLConfigR\x05mysql\x12L\n" +
	"\n" +
	"clickhouse\x18\x03 \x01(\v2,.NYql.Connector.App.Config.TClickHouseConfigR\n" +
	"clickhouse\x12Q\n" +
	"\rms_sql_server\x18\x04 \x01(\v2-.NYql.Connector.App.Config.TMsSQLServerConfigR\vmsSqlServer\x12L\n" +
	"\n" +
	"postgresql\x18\x05 \x01(\v2,.NYql.Connector.App.Config.TPostgreSQLConfigR\n" +
	"postgresql\x12I\n" +
	"\tgreenplum\x18\x06 \x01(\v2+.NYql.Connector.App.Config.TGreenplumConfigR\tgreenplum\x12@\n" +
	"\x06oracle\x18\a \x01(\v2(.NYql.Connector.App.Config.TOracleConfigR\x06oracle\x12C\n" +
	"\alogging\x18\b \x01(\v2).NYql.Connector.App.Config.TLoggingConfigR\alogging\x12C\n" +
	"\amongodb\x18\t \x01(\v2).NYql.Connector.App.Config.TMongoDbConfigR\amongodb\x12=\n" +
	"\x05redis\x18\n" +
	" \x01(\v2'.NYql.Connector.App.Config.TRedisConfigR\x05redis\x12L\n" +
	"\n" +
	"opensearch\x18\v \x01(\v2,.NYql.Connector.App.Config.TOpenSearchConfigR\n" +
	"opensearch*K\n" +
	"\tELogLevel\x12\t\n" +
	"\x05TRACE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05FATAL\x10\x05B4Z2github.com/ydb-platform/fq-connector-go/app/configb\x06proto3"

var (
	file_app_config_server_proto_rawDescOnce sync.Once
	file_app_config_server_proto_rawDescData []byte
)

func file_app_config_server_proto_rawDescGZIP() []byte {
	file_app_config_server_proto_rawDescOnce.Do(func() {
		file_app_config_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_config_server_proto_rawDesc), len(file_app_config_server_proto_rawDesc)))
	})
	return file_app_config_server_proto_rawDescData
}

var file_app_config_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_config_server_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_app_config_server_proto_goTypes = []any{
	(ELogLevel)(0),                                    // 0: NYql.Connector.App.Config.ELogLevel
	(TMongoDbConfig_EObjectIdYqlType)(0),              // 1: NYql.Connector.App.Config.TMongoDbConfig.EObjectIdYqlType
	(TYdbConfig_Mode)(0),                              // 2: NYql.Connector.App.Config.TYdbConfig.Mode
	(*TServerConfig)(nil),                             // 3: NYql.Connector.App.Config.TServerConfig
	(*TConnectorServerConfig)(nil),                    // 4: NYql.Connector.App.Config.TConnectorServerConfig
	(*TServerTLSConfig)(nil),                          // 5: NYql.Connector.App.Config.TServerTLSConfig
	(*TServerReadLimit)(nil),                          // 6: NYql.Connector.App.Config.TServerReadLimit
	(*TLoggerConfig)(nil),                             // 7: NYql.Connector.App.Config.TLoggerConfig
	(*TPprofServerConfig)(nil),                        // 8: NYql.Connector.App.Config.TPprofServerConfig
	(*TMetricsServerConfig)(nil),                      // 9: NYql.Connector.App.Config.TMetricsServerConfig
	(*TPagingConfig)(nil),                             // 10: NYql.Connector.App.Config.TPagingConfig
	(*TConversionConfig)(nil),                         // 11: NYql.Connector.App.Config.TConversionConfig
	(*TExponentialBackoffConfig)(nil),                 // 12: NYql.Connector.App.Config.TExponentialBackoffConfig
	(*TPushdownConfig)(nil),                           // 13: NYql.Connector.App.Config.TPushdownConfig
	(*TClickHouseConfig)(nil),                         // 14: NYql.Connector.App.Config.TClickHouseConfig
	(*TGreenplumConfig)(nil),                          // 15: NYql.Connector.App.Config.TGreenplumConfig
	(*TMsSQLServerConfig)(nil),                        // 16: NYql.Connector.App.Config.TMsSQLServerConfig
	(*TMySQLConfig)(nil),                              // 17: NYql.Connector.App.Config.TMySQLConfig
	(*TOracleConfig)(nil),                             // 18: NYql.Connector.App.Config.TOracleConfig
	(*TMongoDbConfig)(nil),                            // 19: NYql.Connector.App.Config.TMongoDbConfig
	(*TRedisConfig)(nil),                              // 20: NYql.Connector.App.Config.TRedisConfig
	(*TOpenSearchConfig)(nil),                         // 21: NYql.Connector.App.Config.TOpenSearchConfig
	(*TPostgreSQLConfig)(nil),                         // 22: NYql.Connector.App.Config.TPostgreSQLConfig
	(*TYdbConfig)(nil),                                // 23: NYql.Connector.App.Config.TYdbConfig
	(*TLoggingConfig)(nil),                            // 24: NYql.Connector.App.Config.TLoggingConfig
	(*TDatasourcesConfig)(nil),                        // 25: NYql.Connector.App.Config.TDatasourcesConfig
	(*TYdbConfig_TSplitting)(nil),                     // 26: NYql.Connector.App.Config.TYdbConfig.TSplitting
	(*TLoggingConfig_TDynamicResolving)(nil),          // 27: NYql.Connector.App.Config.TLoggingConfig.TDynamicResolving
	(*TLoggingConfig_TStaticResolving)(nil),           // 28: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving
	(*TLoggingConfig_TStaticResolving_TDatabase)(nil), // 29: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TDatabase
	(*TLoggingConfig_TStaticResolving_TFolder)(nil),   // 30: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder
	nil,                             // 31: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.FoldersEntry
	nil,                             // 32: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder.LogGroupsEntry
	(*common.TGenericEndpoint)(nil), // 33: NYql.TGenericEndpoint
}
var file_app_config_server_proto_depIdxs = []int32{
	33, // 0: NYql.Connector.App.Config.TServerConfig.endpoint:type_name -> NYql.TGenericEndpoint
	5,  // 1: NYql.Connector.App.Config.TServerConfig.tls:type_name -> NYql.Connector.App.Config.TServerTLSConfig
	4,  // 2: NYql.Connector.App.Config.TServerConfig.connector_server:type_name -> NYql.Connector.App.Config.TConnectorServerConfig
	6,  // 3: NYql.Connector.App.Config.TServerConfig.read_limit:type_name -> NYql.Connector.App.Config.TServerReadLimit
	7,  // 4: NYql.Connector.App.Config.TServerConfig.logger:type_name -> NYql.Connector.App.Config.TLoggerConfig
	8,  // 5: NYql.Connector.App.Config.TServerConfig.pprof_server:type_name -> NYql.Connector.App.Config.TPprofServerConfig
	9,  // 6: NYql.Connector.App.Config.TServerConfig.metrics_server:type_name -> NYql.Connector.App.Config.TMetricsServerConfig
	10, // 7: NYql.Connector.App.Config.TServerConfig.paging:type_name -> NYql.Connector.App.Config.TPagingConfig
	11, // 8: NYql.Connector.App.Config.TServerConfig.conversion:type_name -> NYql.Connector.App.Config.TConversionConfig
	25, // 9: NYql.Connector.App.Config.TServerConfig.datasources:type_name -> NYql.Connector.App.Config.TDatasourcesConfig
	33, // 10: NYql.Connector.App.Config.TConnectorServerConfig.endpoint:type_name -> NYql.TGenericEndpoint
	5,  // 11: NYql.Connector.App.Config.TConnectorServerConfig.tls:type_name -> NYql.Connector.App.Config.TServerTLSConfig
	0,  // 12: NYql.Connector.App.Config.TLoggerConfig.log_level:type_name -> NYql.Connector.App.Config.ELogLevel
	33, // 13: NYql.Connector.App.Config.TPprofServerConfig.endpoint:type_name -> NYql.TGenericEndpoint
	5,  // 14: NYql.Connector.App.Config.TPprofServerConfig.tls:type_name -> NYql.Connector.App.Config.TServerTLSConfig
	33, // 15: NYql.Connector.App.Config.TMetricsServerConfig.endpoint:type_name -> NYql.TGenericEndpoint
	5,  // 16: NYql.Connector.App.Config.TMetricsServerConfig.tls:type_name -> NYql.Connector.App.Config.TServerTLSConfig
	12, // 17: NYql.Connector.App.Config.TClickHouseConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 18: NYql.Connector.App.Config.TClickHouseConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	12, // 19: NYql.Connector.App.Config.TGreenplumConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 20: NYql.Connector.App.Config.TGreenplumConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	12, // 21: NYql.Connector.App.Config.TMsSQLServerConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 22: NYql.Connector.App.Config.TMsSQLServerConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	12, // 23: NYql.Connector.App.Config.TMySQLConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 24: NYql.Connector.App.Config.TMySQLConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	12, // 25: NYql.Connector.App.Config.TOracleConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 26: NYql.Connector.App.Config.TOracleConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	1,  // 27: NYql.Connector.App.Config.TMongoDbConfig.object_id_yql_type:type_name -> NYql.Connector.App.Config.TMongoDbConfig.EObjectIdYqlType
	12, // 28: NYql.Connector.App.Config.TMongoDbConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	12, // 29: NYql.Connector.App.Config.TRedisConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	12, // 30: NYql.Connector.App.Config.TOpenSearchConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	12, // 31: NYql.Connector.App.Config.TPostgreSQLConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 32: NYql.Connector.App.Config.TPostgreSQLConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	2,  // 33: NYql.Connector.App.Config.TYdbConfig.mode:type_name -> NYql.Connector.App.Config.TYdbConfig.Mode
	33, // 34: NYql.Connector.App.Config.TYdbConfig.iam_endpoint:type_name -> NYql.TGenericEndpoint
	26, // 35: NYql.Connector.App.Config.TYdbConfig.splitting:type_name -> NYql.Connector.App.Config.TYdbConfig.TSplitting
	12, // 36: NYql.Connector.App.Config.TYdbConfig.exponential_backoff:type_name -> NYql.Connector.App.Config.TExponentialBackoffConfig
	13, // 37: NYql.Connector.App.Config.TYdbConfig.pushdown:type_name -> NYql.Connector.App.Config.TPushdownConfig
	23, // 38: NYql.Connector.App.Config.TLoggingConfig.ydb:type_name -> NYql.Connector.App.Config.TYdbConfig
	27, // 39: NYql.Connector.App.Config.TLoggingConfig.dynamic:type_name -> NYql.Connector.App.Config.TLoggingConfig.TDynamicResolving
	28, // 40: NYql.Connector.App.Config.TLoggingConfig.static:type_name -> NYql.Connector.App.Config.TLoggingConfig.TStaticResolving
	23, // 41: NYql.Connector.App.Config.TDatasourcesConfig.ydb:type_name -> NYql.Connector.App.Config.TYdbConfig
	17, // 42: NYql.Connector.App.Config.TDatasourcesConfig.mysql:type_name -> NYql.Connector.App.Config.TMySQLConfig
	14, // 43: NYql.Connector.App.Config.TDatasourcesConfig.clickhouse:type_name -> NYql.Connector.App.Config.TClickHouseConfig
	16, // 44: NYql.Connector.App.Config.TDatasourcesConfig.ms_sql_server:type_name -> NYql.Connector.App.Config.TMsSQLServerConfig
	22, // 45: NYql.Connector.App.Config.TDatasourcesConfig.postgresql:type_name -> NYql.Connector.App.Config.TPostgreSQLConfig
	15, // 46: NYql.Connector.App.Config.TDatasourcesConfig.greenplum:type_name -> NYql.Connector.App.Config.TGreenplumConfig
	18, // 47: NYql.Connector.App.Config.TDatasourcesConfig.oracle:type_name -> NYql.Connector.App.Config.TOracleConfig
	24, // 48: NYql.Connector.App.Config.TDatasourcesConfig.logging:type_name -> NYql.Connector.App.Config.TLoggingConfig
	19, // 49: NYql.Connector.App.Config.TDatasourcesConfig.mongodb:type_name -> NYql.Connector.App.Config.TMongoDbConfig
	20, // 50: NYql.Connector.App.Config.TDatasourcesConfig.redis:type_name -> NYql.Connector.App.Config.TRedisConfig
	21, // 51: NYql.Connector.App.Config.TDatasourcesConfig.opensearch:type_name -> NYql.Connector.App.Config.TOpenSearchConfig
	33, // 52: NYql.Connector.App.Config.TLoggingConfig.TDynamicResolving.logging_endpoint:type_name -> NYql.TGenericEndpoint
	29, // 53: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.databases:type_name -> NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TDatabase
	31, // 54: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.folders:type_name -> NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.FoldersEntry
	33, // 55: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TDatabase.endpoint:type_name -> NYql.TGenericEndpoint
	32, // 56: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder.log_groups:type_name -> NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder.LogGroupsEntry
	30, // 57: NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.FoldersEntry.value:type_name -> NYql.Connector.App.Config.TLoggingConfig.TStaticResolving.TFolder
	58, // [58:58] is the sub-list for method output_type
	58, // [58:58] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_app_config_server_proto_init() }
func file_app_config_server_proto_init() {
	if File_app_config_server_proto != nil {
		return
	}
	file_app_config_server_proto_msgTypes[21].OneofWrappers = []any{
		(*TLoggingConfig_Dynamic)(nil),
		(*TLoggingConfig_Static)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_config_server_proto_rawDesc), len(file_app_config_server_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_config_server_proto_goTypes,
		DependencyIndexes: file_app_config_server_proto_depIdxs,
		EnumInfos:         file_app_config_server_proto_enumTypes,
		MessageInfos:      file_app_config_server_proto_msgTypes,
	}.Build()
	File_app_config_server_proto = out.File
	file_app_config_server_proto_goTypes = nil
	file_app_config_server_proto_depIdxs = nil
}
