// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: ydb/library/yql/providers/generic/connector/api/service/connector.proto

package service

import (
	context "context"
	protos "github.com/ydb-platform/fq-connector-go/api/service/protos"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Connector_ListTables_FullMethodName    = "/NYql.NConnector.NApi.Connector/ListTables"
	Connector_DescribeTable_FullMethodName = "/NYql.NConnector.NApi.Connector/DescribeTable"
	Connector_ListSplits_FullMethodName    = "/NYql.NConnector.NApi.Connector/ListSplits"
	Connector_ReadSplits_FullMethodName    = "/NYql.NConnector.NApi.Connector/ReadSplits"
)

// ConnectorClient is the client API for Connector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Connector provides unified interface for various data sources that can be used to extend capabilities
// of YQ and YQL services.
type ConnectorClient interface {
	// Deprecated: Do not use.
	// ListTables returns the list of tables existing in a particular database.
	ListTables(ctx context.Context, in *protos.TListTablesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TListTablesResponse], error)
	// DescribeTable returns table's schema.
	DescribeTable(ctx context.Context, in *protos.TDescribeTableRequest, opts ...grpc.CallOption) (*protos.TDescribeTableResponse, error)
	// ListSplits asks Connector to partition the data that are going to be read
	// into elementary parts suitable for parallel reading.
	ListSplits(ctx context.Context, in *protos.TListSplitsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TListSplitsResponse], error)
	// ReadSplits reads data associated with splits.
	ReadSplits(ctx context.Context, in *protos.TReadSplitsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TReadSplitsResponse], error)
}

type connectorClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorClient(cc grpc.ClientConnInterface) ConnectorClient {
	return &connectorClient{cc}
}

// Deprecated: Do not use.
func (c *connectorClient) ListTables(ctx context.Context, in *protos.TListTablesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TListTablesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Connector_ServiceDesc.Streams[0], Connector_ListTables_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[protos.TListTablesRequest, protos.TListTablesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ListTablesClient = grpc.ServerStreamingClient[protos.TListTablesResponse]

func (c *connectorClient) DescribeTable(ctx context.Context, in *protos.TDescribeTableRequest, opts ...grpc.CallOption) (*protos.TDescribeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protos.TDescribeTableResponse)
	err := c.cc.Invoke(ctx, Connector_DescribeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) ListSplits(ctx context.Context, in *protos.TListSplitsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TListSplitsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Connector_ServiceDesc.Streams[1], Connector_ListSplits_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[protos.TListSplitsRequest, protos.TListSplitsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ListSplitsClient = grpc.ServerStreamingClient[protos.TListSplitsResponse]

func (c *connectorClient) ReadSplits(ctx context.Context, in *protos.TReadSplitsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.TReadSplitsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Connector_ServiceDesc.Streams[2], Connector_ReadSplits_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[protos.TReadSplitsRequest, protos.TReadSplitsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ReadSplitsClient = grpc.ServerStreamingClient[protos.TReadSplitsResponse]

// ConnectorServer is the server API for Connector service.
// All implementations must embed UnimplementedConnectorServer
// for forward compatibility.
//
// Connector provides unified interface for various data sources that can be used to extend capabilities
// of YQ and YQL services.
type ConnectorServer interface {
	// Deprecated: Do not use.
	// ListTables returns the list of tables existing in a particular database.
	ListTables(*protos.TListTablesRequest, grpc.ServerStreamingServer[protos.TListTablesResponse]) error
	// DescribeTable returns table's schema.
	DescribeTable(context.Context, *protos.TDescribeTableRequest) (*protos.TDescribeTableResponse, error)
	// ListSplits asks Connector to partition the data that are going to be read
	// into elementary parts suitable for parallel reading.
	ListSplits(*protos.TListSplitsRequest, grpc.ServerStreamingServer[protos.TListSplitsResponse]) error
	// ReadSplits reads data associated with splits.
	ReadSplits(*protos.TReadSplitsRequest, grpc.ServerStreamingServer[protos.TReadSplitsResponse]) error
	mustEmbedUnimplementedConnectorServer()
}

// UnimplementedConnectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorServer struct{}

func (UnimplementedConnectorServer) ListTables(*protos.TListTablesRequest, grpc.ServerStreamingServer[protos.TListTablesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedConnectorServer) DescribeTable(context.Context, *protos.TDescribeTableRequest) (*protos.TDescribeTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTable not implemented")
}
func (UnimplementedConnectorServer) ListSplits(*protos.TListSplitsRequest, grpc.ServerStreamingServer[protos.TListSplitsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListSplits not implemented")
}
func (UnimplementedConnectorServer) ReadSplits(*protos.TReadSplitsRequest, grpc.ServerStreamingServer[protos.TReadSplitsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadSplits not implemented")
}
func (UnimplementedConnectorServer) mustEmbedUnimplementedConnectorServer() {}
func (UnimplementedConnectorServer) testEmbeddedByValue()                   {}

// UnsafeConnectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorServer will
// result in compilation errors.
type UnsafeConnectorServer interface {
	mustEmbedUnimplementedConnectorServer()
}

func RegisterConnectorServer(s grpc.ServiceRegistrar, srv ConnectorServer) {
	// If the following call pancis, it indicates UnimplementedConnectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Connector_ServiceDesc, srv)
}

func _Connector_ListTables_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protos.TListTablesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServer).ListTables(m, &grpc.GenericServerStream[protos.TListTablesRequest, protos.TListTablesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ListTablesServer = grpc.ServerStreamingServer[protos.TListTablesResponse]

func _Connector_DescribeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protos.TDescribeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).DescribeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Connector_DescribeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).DescribeTable(ctx, req.(*protos.TDescribeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_ListSplits_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protos.TListSplitsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServer).ListSplits(m, &grpc.GenericServerStream[protos.TListSplitsRequest, protos.TListSplitsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ListSplitsServer = grpc.ServerStreamingServer[protos.TListSplitsResponse]

func _Connector_ReadSplits_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protos.TReadSplitsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServer).ReadSplits(m, &grpc.GenericServerStream[protos.TReadSplitsRequest, protos.TReadSplitsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Connector_ReadSplitsServer = grpc.ServerStreamingServer[protos.TReadSplitsResponse]

// Connector_ServiceDesc is the grpc.ServiceDesc for Connector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Connector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NYql.NConnector.NApi.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeTable",
			Handler:    _Connector_DescribeTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTables",
			Handler:       _Connector_ListTables_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSplits",
			Handler:       _Connector_ListSplits_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadSplits",
			Handler:       _Connector_ReadSplits_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ydb/library/yql/providers/generic/connector/api/service/connector.proto",
}
