// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ydb/library/yql/providers/generic/connector/api/service/connector.proto

package service

import (
	protos "github.com/ydb-platform/fq-connector-go/api/service/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ydb_library_yql_providers_generic_connector_api_service_connector_proto protoreflect.FileDescriptor

const file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_rawDesc = "" +
	"\n" +
	"Gydb/library/yql/providers/generic/connector/api/service/connector.proto\x12\x14NYql.NConnector.NApi\x1aNydb/library/yql/providers/generic/connector/api/service/protos/connector.proto2\xab\x03\n" +
	"\tConnector\x12h\n" +
	"\n" +
	"ListTables\x12(.NYql.NConnector.NApi.TListTablesRequest\x1a).NYql.NConnector.NApi.TListTablesResponse\"\x03\x88\x02\x010\x01\x12j\n" +
	"\rDescribeTable\x12+.NYql.NConnector.NApi.TDescribeTableRequest\x1a,.NYql.NConnector.NApi.TDescribeTableResponse\x12c\n" +
	"\n" +
	"ListSplits\x12(.NYql.NConnector.NApi.TListSplitsRequest\x1a).NYql.NConnector.NApi.TListSplitsResponse0\x01\x12c\n" +
	"\n" +
	"ReadSplits\x12(.NYql.NConnector.NApi.TReadSplitsRequest\x1a).NYql.NConnector.NApi.TReadSplitsResponse0\x01B5Z3github.com/ydb-platform/fq-connector-go/api/serviceb\x06proto3"

var file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_goTypes = []any{
	(*protos.TListTablesRequest)(nil),     // 0: NYql.NConnector.NApi.TListTablesRequest
	(*protos.TDescribeTableRequest)(nil),  // 1: NYql.NConnector.NApi.TDescribeTableRequest
	(*protos.TListSplitsRequest)(nil),     // 2: NYql.NConnector.NApi.TListSplitsRequest
	(*protos.TReadSplitsRequest)(nil),     // 3: NYql.NConnector.NApi.TReadSplitsRequest
	(*protos.TListTablesResponse)(nil),    // 4: NYql.NConnector.NApi.TListTablesResponse
	(*protos.TDescribeTableResponse)(nil), // 5: NYql.NConnector.NApi.TDescribeTableResponse
	(*protos.TListSplitsResponse)(nil),    // 6: NYql.NConnector.NApi.TListSplitsResponse
	(*protos.TReadSplitsResponse)(nil),    // 7: NYql.NConnector.NApi.TReadSplitsResponse
}
var file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_depIdxs = []int32{
	0, // 0: NYql.NConnector.NApi.Connector.ListTables:input_type -> NYql.NConnector.NApi.TListTablesRequest
	1, // 1: NYql.NConnector.NApi.Connector.DescribeTable:input_type -> NYql.NConnector.NApi.TDescribeTableRequest
	2, // 2: NYql.NConnector.NApi.Connector.ListSplits:input_type -> NYql.NConnector.NApi.TListSplitsRequest
	3, // 3: NYql.NConnector.NApi.Connector.ReadSplits:input_type -> NYql.NConnector.NApi.TReadSplitsRequest
	4, // 4: NYql.NConnector.NApi.Connector.ListTables:output_type -> NYql.NConnector.NApi.TListTablesResponse
	5, // 5: NYql.NConnector.NApi.Connector.DescribeTable:output_type -> NYql.NConnector.NApi.TDescribeTableResponse
	6, // 6: NYql.NConnector.NApi.Connector.ListSplits:output_type -> NYql.NConnector.NApi.TListSplitsResponse
	7, // 7: NYql.NConnector.NApi.Connector.ReadSplits:output_type -> NYql.NConnector.NApi.TReadSplitsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_init() }
func file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_init() {
	if File_ydb_library_yql_providers_generic_connector_api_service_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_rawDesc), len(file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_goTypes,
		DependencyIndexes: file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_depIdxs,
	}.Build()
	File_ydb_library_yql_providers_generic_connector_api_service_connector_proto = out.File
	file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_goTypes = nil
	file_ydb_library_yql_providers_generic_connector_api_service_connector_proto_depIdxs = nil
}
