package mysql

const (
	typeInt        = "int"
	typeMediumInt  = "mediumint"
	typeBigInt     = "bigint"
	typeFloat      = "float"
	typeDouble     = "double"
	typeTinyInt    = "tinyint"
	typeSmallInt   = "smallint"
	typeLongBlob   = "longblob"
	typeBlob       = "blob"
	typeMediumBlob = "mediumblob"
	typeTinyBlob   = "tinyblob"
	typeBinary     = "binary"
	typeVarBinary  = "varbinary"
	typeVarChar    = "varchar"
	typeString     = "string"
	typeText       = "text"
	typeLongText   = "longtext"
	typeTinyText   = "tinytext"
	typeMediumText = "mediumtext"
	typeChar       = "char"
	typeDate       = "date"
	typeDatetime   = "datetime"
	typeTimestamp  = "timestamp"
)
