version: '3.8'

services:
  trino:
    image: trinodb/trino:472
    ports:
      - "8080:8080" 
    volumes:
      - ./catalog:/etc/trino/catalog 
    depends_on:
      - postgresql
      - clickhouse

  postgresql:
    image: postgres:17.4
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d

  clickhouse:
    image: mirror.gcr.io/clickhouse/clickhouse-server:24.10.2.80
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: db
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144