action_id: trunk-upgrade-available
date: 2024-05-04 10:13:18
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714817598
full_timestamp:
  nanos: 1725000
  seconds: 1714817598
trunk_version: 1.22.0
