action_id: trunk-upgrade-available
date: 2024-05-03 19:52:10
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1714765930
full_timestamp:
  nanos: 165627000
  seconds: 1714765930
trunk_version: 1.22.0
