// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: app/server/datasource/rdbms/logging/split.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TSplitDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In YDB column shards it
	TabletIds     []uint64 `protobuf:"varint,1,rep,packed,name=tablet_ids,json=tabletIds,proto3" json:"tablet_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSplitDescription) Reset() {
	*x = TSplitDescription{}
	mi := &file_app_server_datasource_rdbms_logging_split_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSplitDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSplitDescription) ProtoMessage() {}

func (x *TSplitDescription) ProtoReflect() protoreflect.Message {
	mi := &file_app_server_datasource_rdbms_logging_split_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSplitDescription.ProtoReflect.Descriptor instead.
func (*TSplitDescription) Descriptor() ([]byte, []int) {
	return file_app_server_datasource_rdbms_logging_split_proto_rawDescGZIP(), []int{0}
}

func (x *TSplitDescription) GetTabletIds() []uint64 {
	if x != nil {
		return x.TabletIds
	}
	return nil
}

var File_app_server_datasource_rdbms_logging_split_proto protoreflect.FileDescriptor

var file_app_server_datasource_rdbms_logging_split_proto_rawDesc = string([]byte{
	0x0a, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72, 0x64, 0x62, 0x6d, 0x73, 0x2f, 0x6c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x32, 0x4e, 0x59, 0x71, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x41, 0x70, 0x70, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x44, 0x42, 0x4d, 0x53, 0x2e, 0x4c, 0x6f,
	0x67, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x32, 0x0a, 0x11, 0x54, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x73, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x66, 0x71, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x72, 0x64, 0x62, 0x6d, 0x73,
	0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_app_server_datasource_rdbms_logging_split_proto_rawDescOnce sync.Once
	file_app_server_datasource_rdbms_logging_split_proto_rawDescData []byte
)

func file_app_server_datasource_rdbms_logging_split_proto_rawDescGZIP() []byte {
	file_app_server_datasource_rdbms_logging_split_proto_rawDescOnce.Do(func() {
		file_app_server_datasource_rdbms_logging_split_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_server_datasource_rdbms_logging_split_proto_rawDesc), len(file_app_server_datasource_rdbms_logging_split_proto_rawDesc)))
	})
	return file_app_server_datasource_rdbms_logging_split_proto_rawDescData
}

var file_app_server_datasource_rdbms_logging_split_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_server_datasource_rdbms_logging_split_proto_goTypes = []any{
	(*TSplitDescription)(nil), // 0: NYql.Connector.App.Server.DataSource.RDBMS.Logging.TSplitDescription
}
var file_app_server_datasource_rdbms_logging_split_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_server_datasource_rdbms_logging_split_proto_init() }
func file_app_server_datasource_rdbms_logging_split_proto_init() {
	if File_app_server_datasource_rdbms_logging_split_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_server_datasource_rdbms_logging_split_proto_rawDesc), len(file_app_server_datasource_rdbms_logging_split_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_server_datasource_rdbms_logging_split_proto_goTypes,
		DependencyIndexes: file_app_server_datasource_rdbms_logging_split_proto_depIdxs,
		MessageInfos:      file_app_server_datasource_rdbms_logging_split_proto_msgTypes,
	}.Build()
	File_app_server_datasource_rdbms_logging_split_proto = out.File
	file_app_server_datasource_rdbms_logging_split_proto_goTypes = nil
	file_app_server_datasource_rdbms_logging_split_proto_depIdxs = nil
}
