version: '3'

services:

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: fq-connector-go-bench-clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_DB: tpch
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/data/:/var/lib/clickhouse/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  postgresql:
    image: postgres:15.3
    container_name: fq-connector-go-bench-postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: tpch
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/
