// Code generated by "stringer -type=sinkFactoryState"; DO NOT EDIT.

package paging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sinkFactoryOperational-0]
	_ = x[sinkFactoryTerminating-1]
	_ = x[sinkFactoryTerminated-2]
}

const _sinkFactoryState_name = "sinkFactoryOperationalsinkFactoryTerminatingsinkFactoryTerminated"

var _sinkFactoryState_index = [...]uint8{0, 22, 44, 65}

func (i sinkFactoryState) String() string {
	if i < 0 || i >= sinkFactoryState(len(_sinkFactoryState_index)-1) {
		return "sinkFactoryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sinkFactoryState_name[_sinkFactoryState_index[i]:_sinkFactoryState_index[i+1]]
}
