name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tests/infra/datasource/ms_sql_server/init/**'
      - 'tests/infra/datasource/opensearch/init/**'
      - '.github/workflows/build-docker-images.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tests/infra/datasource/ms_sql_server/init/**'
      - 'tests/infra/datasource/opensearch/init/**'
      - '.github/workflows/build-docker-images.yml'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for MS SQL Server
        id: meta-mssql
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ms_sql_server-test
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push MS SQL Server image
        uses: docker/build-push-action@v5
        with:
          context: ./tests/infra/datasource/ms_sql_server/init
          push: true
          tags: ${{ steps.meta-mssql.outputs.tags }}
          labels: ${{ steps.meta-mssql.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for OpenSearch
        id: meta-opensearch
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/opensearch-test
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build and push OpenSearch image
        uses: docker/build-push-action@v5
        with:
          context: ./tests/infra/datasource/opensearch/init
          push: true
          tags: ${{ steps.meta-opensearch.outputs.tags }}
          labels: ${{ steps.meta-opensearch.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max